version: "3.4"

# Development environment override
services:
  php:
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./src/backend/:/var/www/site:rw,cached
      - ./docker/images/symfony_php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini

