# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
    - { resource: services/* }
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'ru'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            string $projectDir: '%kernel.project_dir%'

    App\Infrastructure\EventSubscriber\ApiExceptionSubscriber:
        autowire: true
        tags:
            - { name: kernel.event_subscriber, event: kernel.exception }

#    App\Service\CountryDefine:
#        autowire: true
#        argument:

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Infrastructure/{RequestData,Exception,Response}/*'
            - '../src/Infrastructure/Service/Tax/FormatToRegConverter/*'
            - '../src/Infrastructure/Service/Payment/*'
            - '../src/{DataTransfer}/*'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
#    App\Controller\:
#        resource: '../src/Controller/**/*'
#        tags: [ 'controller.service_arguments' ]
#        calls:
#            - [ setNormalizer, [ '@App\Infrastructure\Normalizer\ObjectToArrayNormalizer' ] ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
